version: "3"
services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file:
      - ./docker/env
    volumes:
    #  - ./app:/srv/app

      - ./app/public:/srv/app/public
      - ./app/class:/srv/app/class
